### ISSUE TITLE
Trumpline

### ISSUE THREAD

**Issue by athoug** [athoug/Trumpland#1]
So the to-dos for this stage would be: 

- [x] scrape Trumps timeline for data to have an array of possible real tweets
- [x] for fake tweets perhaps scrape the twitter bot? [whatever way you want to do it mike is cool :) ]
- [x] add tags for the fake and real to check for correctness [that's how I did it but you can do the check any way you want]
- [x] randomly instantiate these tweets 
- [ ] add the logic and brick count

**Comment by tqy202** [comment]
Screen scraping is not needed, use the twitter api:
https://dev.twitter.com/docs

**Comment by athoug** [comment]
That would work too, it even looks like there are a couple of libraries for c# https://dev.twitter.com/resources/twitter-libraries

**Comment by mcgreentn** [comment]
Pulled some 6k tweets, half from real donald and half fake, to be used as a tweet bank.

Tweets are randomly pulled with a 50% chance of grabbing one or the other.
