### ISSUE TITLE
Immigrants

### ISSUE THREAD

**Issue by athoug** [athoug/Trumpland#2]
The to-do's for this one:

- [x] an array of the different locations for each person
- [x] an array of their velocity
- [x] randomly generate them 
- [x] add the logic and brick count
- [x] add the animation of items

**Comment by athoug** [comment]
finished object animation of people and plane script

**Comment by athoug** [comment]
finished the logic for both the bricks and people

**Comment by athoug** [comment]
instead of array, I added a script that randomly positions them and based on their location it adjusts the layer order so they are positioned correctly.

**Comment by athoug** [comment]
Finished the immigrant prefab panel

**Comment by mcgreentn** [comment]
Closing for now
