### ISSUE TITLE
Carousel Scene Manager

### ISSUE THREAD

**Issue by athoug** [athoug/Trumpland#4]
- [x] Adding the switch between stages effect

**Comment by mcgreentn** [comment]
Found the perfect tutorial for this. It's 5 parts, roughly twenty minutes each. Hopefully in under two hours from starting work on it, I'll have built us a game carousel!

Link here: https://youtu.be/9B7ahj1kaYs

**Comment by athoug** [comment]
That's brilliant!

**Comment by mcgreentn** [comment]
Closed for now, Navigation is currently covered in #6
